create table if not exists releases (
    github_release_id bigint primary key,
    tag text not null unique,
    name text,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists release_assets (
    github_asset_id bigint primary key,
    github_release_id bigint not null references releases(github_release_id) on delete cascade,
    name text not null,
    size_bytes bigint not null default 0,
    content_type text,
    is_installer boolean not null default false,
    is_latest_alias boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists download_snapshots (
    id bigint generated by default as identity primary key,
    github_asset_id bigint not null references release_assets(github_asset_id) on delete cascade,
    snapshot_date date not null,
    recorded_at timestamptz not null default now(),
    download_count bigint not null check (download_count >= 0),
    unique(github_asset_id, snapshot_date)
);

create index if not exists idx_release_assets_release on release_assets(github_release_id);
create index if not exists idx_download_snapshots_asset on download_snapshots(github_asset_id);
create index if not exists idx_download_snapshots_date on download_snapshots(snapshot_date);
create index if not exists idx_download_snapshots_asset_date on download_snapshots(github_asset_id, snapshot_date);

create or replace function set_analytics_updated_at() returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists releases_set_updated_at on releases;
create trigger releases_set_updated_at before update on releases
for each row execute function set_analytics_updated_at();

drop trigger if exists release_assets_set_updated_at on release_assets;
create trigger release_assets_set_updated_at before update on release_assets
for each row execute function set_analytics_updated_at();

create or replace view download_snapshot_deltas as
select ds.id, ds.github_asset_id, ra.github_release_id, r.tag, ra.name as asset_name,
       ra.is_installer, ra.is_latest_alias, ds.snapshot_date, ds.recorded_at,
       ds.download_count,
       lag(ds.download_count) over (partition by ds.github_asset_id order by ds.snapshot_date)
           as previous_download_count
from download_snapshots ds
join release_assets ra on ra.github_asset_id = ds.github_asset_id
join releases r on r.github_release_id = ra.github_release_id;

create or replace view download_daily as
select github_asset_id, github_release_id, tag, asset_name, is_installer,
       is_latest_alias, snapshot_date, download_count, previous_download_count,
       case when previous_download_count is null then download_count
            when download_count >= previous_download_count then download_count - previous_download_count
            else 0 end as new_downloads,
       previous_download_count is not null and download_count < previous_download_count
           as count_reset_detected
from download_snapshot_deltas;

create or replace view installer_daily_totals as
select snapshot_date, sum(new_downloads) as downloads
from download_daily where is_installer = true group by snapshot_date order by snapshot_date;

create or replace view installer_downloads_by_version as
select tag, sum(new_downloads) as downloads
from download_daily where is_installer = true group by tag order by tag;

alter table releases enable row level security;
alter table release_assets enable row level security;
alter table download_snapshots enable row level security;
