import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from "react";
import type { User } from "@supabase/supabase-js";
import docSyncLogo from "./assets/Docsync LOGO.png";
import { authConfigured, supabase } from "./auth";

export type AccountRole = "user" | "admin";
type MigrationState = "none" | "migration_ready" | "migration_copying" | "migration_validating" | "migration_complete" | "migration_failed" | "migration_declined" | "migration_conflict";
type AuthContextValue = { user: User; role: AccountRole; signOut: () => Promise<void> };
const AuthContext = createContext<AuthContextValue | null>(null);
export function useAuthenticatedUser(): AuthContextValue { const value = useContext(AuthContext); if (!value) throw new Error("AuthAccount must be rendered after authentication."); return value; }
async function getRole(userId: string): Promise<AccountRole> { const { data, error } = await supabase!.from("user_roles").select("role").eq("user_id", userId).maybeSingle(); return !error && data?.role === "admin" ? "admin" : "user"; }

export default function AuthGate({ children }: { children: ReactNode }) {
  const [state, setState] = useState<"loading_auth" | "signed_out" | "signing_in" | "activating_account" | "signed_in" | "error">("loading_auth");
  const [user, setUser] = useState<User | null>(null); const [role, setRole] = useState<AccountRole>("user"); const [error, setError] = useState(""); const [migration, setMigration] = useState<MigrationState>("none"); const client = supabase;
  const activate = useCallback(async (nextUser: User) => { setState("activating_account"); const result = await window.docSync?.activateAccount(nextUser.id); if (!result?.workspace_ready) throw new Error("Account workspace could not be activated."); setMigration(result.state); setUser(nextUser); setRole(await getRole(nextUser.id)); setState("signed_in"); }, []);
  const restore = useCallback(async () => { if (!client) { setState("error"); setError("DocSync account services are not configured."); return; } setState("loading_auth"); setError(""); try { const { data: sessionData, error: sessionError } = await client.auth.getSession(); if (sessionError || !sessionData.session) { setUser(null); setState("signed_out"); return; } const { data, error: userError } = await client.auth.getUser(); if (userError || !data.user) { await client.auth.signOut(); setUser(null); setState("signed_out"); return; } await activate(data.user); } catch { setUser(null); setError("Could not connect to DocSync account services."); setState("error"); } }, [activate, client]);
  const exchange = useCallback(async (code: string) => { if (!client) return; setState("signing_in"); setError(""); const { data, error: exchangeError } = await client.auth.exchangeCodeForSession(code); if (exchangeError || !data.user) { if (exchangeError) console.error("DocSync OAuth code exchange failed:", exchangeError); setError("Sign-in could not be completed."); setState("error"); return; } try { await activate(data.user); } catch { setError("Account workspace could not be activated."); setState("error"); } }, [activate, client]);
  useEffect(() => { const initialise = async () => { const code = await window.docSync?.getAuthCallback(); if (code) await exchange(code); else await restore(); }; void initialise(); const unsubscribe = window.docSync?.onAuthCallback((code) => void exchange(code)); return unsubscribe; }, [exchange, restore]);
  const signIn = async () => { if (!client) return; setState("signing_in"); setError(""); const { data, error: signInError } = await client.auth.signInWithOAuth({ provider: "google", options: { redirectTo: "za.co.docsync://auth/callback", skipBrowserRedirect: true } }); if (signInError || !data.url || !(await window.docSync?.openOAuth(data.url))) { setError("Could not open Google sign-in."); setState("error"); } };
  const signOut = async () => { setUser(null); setState("loading_auth"); await window.docSync?.deactivateAccount(); await client?.auth.signOut(); await window.docSync?.authStorage?.clear(); setMigration("none"); setRole("user"); setState("signed_out"); };
  const importLegacy = async () => { setMigration("migration_copying"); setError(""); try { setMigration("migration_validating"); const result = await window.docSync?.importLegacyWorkspace(); setMigration(result?.state || "migration_complete"); } catch { setMigration("migration_failed"); setError("Your existing DocSync workspace was not changed. The import could not be completed."); } };
  const declineLegacy = async () => { const result = await window.docSync?.declineLegacyMigration(); setMigration(result?.state || "migration_declined"); };
  if (state === "loading_auth" || state === "signing_in" || state === "activating_account") return <main className="auth-screen auth-loading"><img src={docSyncLogo} alt="DocSync" /><p>{state === "activating_account" ? "Opening your local workspace..." : state === "signing_in" ? "Completing sign-in..." : "Opening DocSync..."}</p></main>;
  if (state === "signed_in" && user) return <AuthContext.Provider value={{ user, role, signOut }}>{migration === "migration_ready" && <LegacyMigrationPrompt onImport={() => void importLegacy()} onDecline={() => void declineLegacy()} busy={false} />}{migration === "migration_copying" || migration === "migration_validating" ? <LegacyMigrationPrompt onImport={() => undefined} onDecline={() => undefined} busy /> : null}{migration === "migration_failed" && <LegacyMigrationPrompt onImport={() => void importLegacy()} onDecline={() => void declineLegacy()} busy={false} error={error} />}{children}</AuthContext.Provider>;
  return <main className="auth-screen"><section className="auth-card"><img src={docSyncLogo} alt="DocSync" /><h1>Welcome to DocSync</h1><p>Keep your documents consistent without giving up control.</p>{authConfigured && <button type="button" className="primary-button" onClick={() => void signIn()}>Continue with Google</button>}{state === "error" && <div role="alert"><p>{error}</p><button type="button" className="quiet-button" onClick={() => void restore()}>Retry</button></div>}<small>Your documents remain stored locally on this computer.</small></section></main>;
}
function LegacyMigrationPrompt({ onImport, onDecline, busy, error }: { onImport: () => void; onDecline: () => void; busy: boolean; error?: string }) { return <div className="migration-backdrop" role="presentation"><section className="migration-dialog" role="dialog" aria-modal="true" aria-labelledby="legacy-migration-title"><h2 id="legacy-migration-title">Existing DocSync documents were found on this computer.</h2><p>{error || (busy ? "Preparing a safe copy of your existing workspace..." : "Would you like to add them to this account?")}</p><small>Your existing workspace will remain unchanged.</small><div>{!busy && <button type="button" className="primary-button" onClick={onImport}>Add to this account</button>} {!busy && <button type="button" className="quiet-button" onClick={onDecline}>Not now</button>}</div></section></div>; }
