import { useCallback, useEffect, useRef, useState } from "react";
import { CloudSnapshotRepository, snapshotObjectKeyFor, SnapshotProviderError, SupabaseWorkspaceSnapshotProvider } from "./cloudSnapshots";
import { supabase } from "./auth";
import { useAuthenticatedUser } from "./AuthGate";

type BackupState = "clean" | "dirty" | "snapshot_creating" | "uploading" | "promoting" | "synced" | "backup_failed" | "conflict";
type LocalState = { state: BackupState; revision?: number; snapshot_id?: string; last_successful_backup?: string; dirty_generation?: number; pending_snapshot_id?: string };
const initial: LocalState = { state: "clean", dirty_generation: 0 };

export default function CloudBackup() {
  const { user, deviceId } = useAuthenticatedUser(); const [local, setLocal] = useState<LocalState>(initial); const busy = useRef(false); const generation = useRef(0); const timer = useRef<number | undefined>(undefined);
  const persist = useCallback(async (next: LocalState) => { setLocal(next); await window.docSync?.cloudBackup?.setState(next); }, []);
  const backup = useCallback(async () => {
    if (!supabase || busy.current || !deviceId) return; busy.current = true; const started = generation.current;
    try {
      await persist({ ...local, state: "snapshot_creating", dirty_generation: started });
      const created = await fetch("/api/cloud-snapshots", { method: "POST" }); if (!created.ok) throw new Error("snapshot");
      const snapshot = await created.json() as { snapshot_id: string; sha256: string; archive_size_bytes: number; workspace_revision: number };
      const provider = new SupabaseWorkspaceSnapshotProvider(supabase); const repository = new CloudSnapshotRepository(supabase);
      const head = await repository.getCurrentHead(); const objectKey = snapshotObjectKeyFor(user.id, snapshot.snapshot_id);
      await repository.registerDevice(deviceId, "1.18.0");
      await repository.createPendingSnapshot({ id: snapshot.snapshot_id, user_id: user.id, device_id: deviceId, storage_provider: "supabase", storage_bucket: "docsync-workspaces", storage_object_key: objectKey, sha256: snapshot.sha256, archive_size_bytes: snapshot.archive_size_bytes, workspace_revision: snapshot.workspace_revision, base_snapshot_id: head?.snapshot_id ?? null, docsync_version: "1.18.0", database_schema_version: 9 });
      await persist({ ...local, state: "uploading", pending_snapshot_id: snapshot.snapshot_id, dirty_generation: started });
      const archive = await fetch(`/api/cloud-snapshots/${snapshot.snapshot_id}/archive`); if (!archive.ok) throw new Error("archive"); await provider.uploadSnapshot(snapshot.snapshot_id, await archive.blob());
      const metadata = await provider.metadata(snapshot.snapshot_id); if (!metadata || metadata.size !== snapshot.archive_size_bytes) throw new Error("verification");
      await repository.markSnapshotUploaded(snapshot.snapshot_id); await persist({ ...local, state: "promoting", pending_snapshot_id: snapshot.snapshot_id, dirty_generation: started });
      const promoted = await repository.promoteSnapshot(snapshot.snapshot_id, head?.snapshot_id ?? null, head?.workspace_revision ?? 0) as { status?: string; workspace_revision?: number };
      if (promoted.status === "conflict") { await persist({ ...local, state: "conflict", pending_snapshot_id: snapshot.snapshot_id, dirty_generation: generation.current }); return; }
      await persist({ state: generation.current === started ? "synced" : "dirty", revision: promoted.workspace_revision, snapshot_id: snapshot.snapshot_id, last_successful_backup: new Date().toISOString(), dirty_generation: generation.current });
    } catch (error) { const state = error instanceof SnapshotProviderError && error.code === "permission_denied" ? "backup_failed" : "backup_failed"; await persist({ ...local, state, dirty_generation: generation.current }); }
    finally { busy.current = false; if (generation.current > started) { window.clearTimeout(timer.current); timer.current = window.setTimeout(() => void backup(), 30_000); } }
  }, [deviceId, local, persist, user.id]);
  const restoreLatest = useCallback(async () => { if (!supabase || busy.current) return; busy.current = true; try { await persist({ ...local, state: "snapshot_creating" }); const repository = new CloudSnapshotRepository(supabase); const provider = new SupabaseWorkspaceSnapshotProvider(supabase); const head = await repository.getCurrentHead(); if (!head?.snapshot_id) return; const metadata = await repository.getSnapshot(head.snapshot_id); if (!metadata || metadata.user_id !== user.id) throw new Error("ownership"); const archive = await provider.downloadSnapshot(head.snapshot_id); const digest = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", await archive.arrayBuffer()))).map((value) => value.toString(16).padStart(2, "0")).join(""); if (digest !== metadata.sha256) throw new Error("hash"); const form = new FormData(); form.append("archive", archive, `${head.snapshot_id}.zip`); form.append("sha256", metadata.sha256); const staged = await fetch("/api/cloud-restores", { method: "POST", body: form }); if (!staged.ok) throw new Error("restore"); const result = await staged.json() as { snapshot_id: string }; if (!(await window.docSync?.promoteCloudRestore(result.snapshot_id))) throw new Error("promotion"); await persist({ state: "synced", snapshot_id: head.snapshot_id, revision: head.workspace_revision, last_successful_backup: new Date().toISOString(), dirty_generation: generation.current }); window.location.reload(); } catch { await persist({ ...local, state: "backup_failed" }); } finally { busy.current = false; } }, [local, persist, user.id]);
  const checkCloud = useCallback(async () => { if (!supabase) return; try { const head = await new CloudSnapshotRepository(supabase).getCurrentHead(); if (!head) return; if (!local.revision || head.workspace_revision > local.revision) await persist({ ...local, state: local.state === "dirty" ? "conflict" : "clean", pending_snapshot_id: head.snapshot_id, revision: local.revision }); } catch { /* Cloud availability never blocks local editing. */ } }, [local, persist]);
  useEffect(() => { void window.docSync?.cloudBackup?.getState().then((value) => { const recovered = value as Partial<LocalState>; setLocal(["snapshot_creating", "uploading", "promoting"].includes(recovered.state || "") ? { ...recovered, state: "backup_failed" } as LocalState : { ...initial, ...recovered }); }); void checkCloud(); }, []);
  useEffect(() => { const dirty = () => { generation.current += 1; void persist({ ...local, state: "dirty", dirty_generation: generation.current }); window.clearTimeout(timer.current); timer.current = window.setTimeout(() => void backup(), 30_000); }; window.addEventListener("docsync:workspace-mutated", dirty); return () => { window.removeEventListener("docsync:workspace-mutated", dirty); window.clearTimeout(timer.current); }; }, [backup, local, persist]);
  const label = local.state === "synced" ? "✓ Backed up" : local.state === "dirty" ? "Backup pending" : local.state === "backup_failed" ? "Backup failed — changes saved locally" : local.state === "conflict" ? "Conflict — local work preserved" : ["snapshot_creating", "uploading", "promoting"].includes(local.state) ? "Backing up…" : "Cloud unavailable";
  return <div className="cloud-backup"><span title={local.last_successful_backup ? `Last backup: ${new Date(local.last_successful_backup).toLocaleString()}` : undefined}>{label}</span>{local.state === "conflict" && <span title="A newer DocSync workspace was backed up from another computer. Your local changes are safe and will not be overwritten automatically.">Newer cloud backup available</span>}<button type="button" className="quiet-button" disabled={busy.current} onClick={() => void backup()}>{local.state === "backup_failed" ? "Retry" : "Back up now"}</button><button type="button" className="quiet-button" disabled={busy.current} onClick={() => void checkCloud()}>Check cloud status</button>{local.pending_snapshot_id && local.state !== "dirty" && <button type="button" className="quiet-button" disabled={busy.current} onClick={() => void restoreLatest()}>Restore latest cloud backup</button>}</div>;
}
